-- Criação do banco
CREATE DATABASE VETERINARIA;
GO

-- Selecionar banco
USE VETERINARIA;
GO

-- Tabela de tipos de animais
CREATE TABLE TIPO_ANIMAIS (
    ID_TIPO_ANIMAL INT PRIMARY KEY IDENTITY(1,1),
    NOME_TIPO VARCHAR(50) NOT NULL
);
GO

-- Tabela de animais
CREATE TABLE ANIMAIS (
    ID_ANIMAL INT PRIMARY KEY IDENTITY(1,1),
    NOME_ANIMAL VARCHAR(100) NOT NULL,
    ID_TIPO_ANIMAL INT NOT NULL,
    DATA_NASCIMENTO DATE,
    COR VARCHAR(50),
    PESO DECIMAL(6,3) NOT NULL CHECK (PESO > 0),
    ALTURA DECIMAL(4,3) NOT NULL CHECK (ALTURA > 0),
    FOREIGN KEY (ID_TIPO_ANIMAL) REFERENCES TIPO_ANIMAIS(ID_TIPO_ANIMAL)
);
GO

-- Tabela de vacinas
CREATE TABLE VACINAS (
    ID_VACINA INT PRIMARY KEY IDENTITY(1,1),
    NOME_VACINA VARCHAR(100) NOT NULL,
    DATA_APLICACAO DATE NOT NULL,
    ID_ANIMAL INT NOT NULL,
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAIS(ID_ANIMAL)
);
GO

-- Inserção dos tipos de animais
INSERT INTO TIPO_ANIMAIS (NOME_TIPO) VALUES 
('Canino'),
('Felino'),
('Suíno'),
('Caprino'),
('Equino');
GO

-- Inserção dos animais
INSERT INTO ANIMAIS (NOME_ANIMAL, ID_TIPO_ANIMAL, DATA_NASCIMENTO, COR, PESO, ALTURA) VALUES
('Rex', 1, '2020-05-10', 'Marrom', 35.750, 0.850),
('Mimi', 2, '2021-08-15', 'Branco', 4.200, 0.250),
('Bacon', 3, '2022-03-20', 'Rosa', 120.000, 0.900),
('Belinha', 4, '2021-06-05', 'Branco', 55.500, 0.700),
('Relâmpago', 5, '2019-09-12', 'Preto', 500.000, 1.600);
GO

-- Inserção das vacinas
-- Rex (ID 1)
INSERT INTO VACINAS (NOME_VACINA, DATA_APLICACAO, ID_ANIMAL) VALUES
('V8', '2023-02-15', 1),
('Antirrábica', '2023-03-10', 1),
('Giárdia', '2023-04-05', 1);

-- Mimi (ID 2)
INSERT INTO VACINAS (NOME_VACINA, DATA_APLICACAO, ID_ANIMAL) VALUES
('Tríplice Viral Felina', '2023-05-20', 2),
('Antirrábica Felina', '2023-06-10', 2);

-- Bacon (ID 3)
INSERT INTO VACINAS (NOME_VACINA, DATA_APLICACAO, ID_ANIMAL) VALUES
('CircoVírus', '2023-01-25', 3),
('Mycoplasma', '2023-02-28', 3);

-- Belinha (ID 4)
INSERT INTO VACINAS (NOME_VACINA, DATA_APLICACAO, ID_ANIMAL) VALUES
('Clostridioses', '2023-07-15', 4);

-- Relâmpago (ID 5)
INSERT INTO VACINAS (NOME_VACINA, DATA_APLICACAO, ID_ANIMAL) VALUES
('Influenza Equina', '2023-08-22', 5),
('Tétano', '2023-09-05', 5),
('Raiva Equina', '2023-09-10', 5);
GO

-- Consultas

-- Tipos de animais
SELECT * FROM TIPO_ANIMAIS;

-- Animais com tipos
SELECT A.ID_ANIMAL, A.NOME_ANIMAL, T.NOME_TIPO, A.DATA_NASCIMENTO, A.COR, A.PESO, A.ALTURA
FROM ANIMAIS A
JOIN TIPO_ANIMAIS T ON A.ID_TIPO_ANIMAL = T.ID_TIPO_ANIMAL;

-- Vacinas por animal
SELECT V.ID_VACINA, V.NOME_VACINA, V.DATA_APLICACAO, A.NOME_ANIMAL
FROM VACINAS V
JOIN ANIMAIS A ON V.ID_ANIMAL = A.ID_ANIMAL
ORDER BY A.NOME_ANIMAL, V.DATA_APLICACAO;
